=begin
#Tatum API

## Authentication  <!-- ReDoc-Inject: <security-definitions> -->

OpenAPI spec version: 3.9.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.31
=end

require 'date'

module Tatum
  class Transaction
    # Source account - source of transaction(s)
    attr_accessor :account_id

    # Counter account - transaction(s) destination account. In case of blockchain recipient, this is addess of blockchain account.
    attr_accessor :counter_account_id

    # Transaction currency
    attr_accessor :currency

    # Amount in account's currency
    attr_accessor :amount

    # Whether the transaction is anonymous. If true, counter account owner does not see source account.
    attr_accessor :anonymous

    # Time in UTC of transaction.
    attr_accessor :created

    attr_accessor :market_value

    # Type of operation.
    attr_accessor :operation_type

    # Type of payment.
    attr_accessor :transaction_type

    # Transaction internal reference - unique identifier within Tatum ledger. In order of failure, use this value to search for problems.
    attr_accessor :reference

    # For bookkeeping to distinct transaction purpose.
    attr_accessor :transaction_code

    # Note visible for sender.
    attr_accessor :sender_note

    # Note visible for both sender and recipient.
    attr_accessor :recipient_note

    # Payment ID defined in payment order by sender.
    attr_accessor :payment_id

    # Present only for operationType WITHDRAWAL and XLM / XRP based accounts it represents message or destinationTag of the recipient, if present.
    attr_accessor :attr

    # For operationType DEPOSIT it represents address, on which was deposit credited for the account.
    attr_accessor :address

    # For operationType DEPOSIT, BLOCKCHAIN_TRANSACTION it represents transaction id, for which deposit occured.
    attr_accessor :tx_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'account_id' => :'accountId',
        :'counter_account_id' => :'counterAccountId',
        :'currency' => :'currency',
        :'amount' => :'amount',
        :'anonymous' => :'anonymous',
        :'created' => :'created',
        :'market_value' => :'marketValue',
        :'operation_type' => :'operationType',
        :'transaction_type' => :'transactionType',
        :'reference' => :'reference',
        :'transaction_code' => :'transactionCode',
        :'sender_note' => :'senderNote',
        :'recipient_note' => :'recipientNote',
        :'payment_id' => :'paymentId',
        :'attr' => :'attr',
        :'address' => :'address',
        :'tx_id' => :'txId'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'account_id' => :'Object',
        :'counter_account_id' => :'Object',
        :'currency' => :'Object',
        :'amount' => :'Object',
        :'anonymous' => :'Object',
        :'created' => :'Object',
        :'market_value' => :'Object',
        :'operation_type' => :'Object',
        :'transaction_type' => :'Object',
        :'reference' => :'Object',
        :'transaction_code' => :'Object',
        :'sender_note' => :'Object',
        :'recipient_note' => :'Object',
        :'payment_id' => :'Object',
        :'attr' => :'Object',
        :'address' => :'Object',
        :'tx_id' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Tatum::Transaction` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Tatum::Transaction`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      end

      if attributes.key?(:'counter_account_id')
        self.counter_account_id = attributes[:'counter_account_id']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'anonymous')
        self.anonymous = attributes[:'anonymous']
      end

      if attributes.key?(:'created')
        self.created = attributes[:'created']
      end

      if attributes.key?(:'market_value')
        self.market_value = attributes[:'market_value']
      end

      if attributes.key?(:'operation_type')
        self.operation_type = attributes[:'operation_type']
      end

      if attributes.key?(:'transaction_type')
        self.transaction_type = attributes[:'transaction_type']
      end

      if attributes.key?(:'reference')
        self.reference = attributes[:'reference']
      end

      if attributes.key?(:'transaction_code')
        self.transaction_code = attributes[:'transaction_code']
      end

      if attributes.key?(:'sender_note')
        self.sender_note = attributes[:'sender_note']
      end

      if attributes.key?(:'recipient_note')
        self.recipient_note = attributes[:'recipient_note']
      end

      if attributes.key?(:'payment_id')
        self.payment_id = attributes[:'payment_id']
      end

      if attributes.key?(:'attr')
        self.attr = attributes[:'attr']
      end

      if attributes.key?(:'address')
        self.address = attributes[:'address']
      end

      if attributes.key?(:'tx_id')
        self.tx_id = attributes[:'tx_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @account_id.nil?
        invalid_properties.push('invalid value for "account_id", account_id cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @amount.nil?
        invalid_properties.push('invalid value for "amount", amount cannot be nil.')
      end

      if @anonymous.nil?
        invalid_properties.push('invalid value for "anonymous", anonymous cannot be nil.')
      end

      if @created.nil?
        invalid_properties.push('invalid value for "created", created cannot be nil.')
      end

      if @market_value.nil?
        invalid_properties.push('invalid value for "market_value", market_value cannot be nil.')
      end

      if @operation_type.nil?
        invalid_properties.push('invalid value for "operation_type", operation_type cannot be nil.')
      end

      if @transaction_type.nil?
        invalid_properties.push('invalid value for "transaction_type", transaction_type cannot be nil.')
      end

      if @reference.nil?
        invalid_properties.push('invalid value for "reference", reference cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @account_id.nil?
      return false if @currency.nil?
      return false if @amount.nil?
      return false if @anonymous.nil?
      return false if @created.nil?
      return false if @market_value.nil?
      return false if @operation_type.nil?
      operation_type_validator = EnumAttributeValidator.new('Object', ['PAYMENT', 'WITHDRAWAL', 'BLOCKCHAIN_TRANSACTION', 'EXCHANGE', 'FAILED', 'DEPOSIT', 'MINT', 'REVOKE'])
      return false unless operation_type_validator.valid?(@operation_type)
      return false if @transaction_type.nil?
      transaction_type_validator = EnumAttributeValidator.new('Object', ['FAILED', 'DEBIT_PAYMENT', 'CREDIT_PAYMENT', 'CREDIT_DEPOSIT', 'DEBIT_WITHDRAWAL', 'CANCEL_WITHDRAWAL', 'DEBIT_OUTGOING_PAYMENT', 'CREDIT_INCOMING_PAYMENT', 'EXCHANGE_BUY', 'EXCHANGE_SELL'])
      return false unless transaction_type_validator.valid?(@transaction_type)
      return false if @reference.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] operation_type Object to be assigned
    def operation_type=(operation_type)
      validator = EnumAttributeValidator.new('Object', ['PAYMENT', 'WITHDRAWAL', 'BLOCKCHAIN_TRANSACTION', 'EXCHANGE', 'FAILED', 'DEPOSIT', 'MINT', 'REVOKE'])
      unless validator.valid?(operation_type)
        fail ArgumentError, "invalid value for \"operation_type\", must be one of #{validator.allowable_values}."
      end
      @operation_type = operation_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] transaction_type Object to be assigned
    def transaction_type=(transaction_type)
      validator = EnumAttributeValidator.new('Object', ['FAILED', 'DEBIT_PAYMENT', 'CREDIT_PAYMENT', 'CREDIT_DEPOSIT', 'DEBIT_WITHDRAWAL', 'CANCEL_WITHDRAWAL', 'DEBIT_OUTGOING_PAYMENT', 'CREDIT_INCOMING_PAYMENT', 'EXCHANGE_BUY', 'EXCHANGE_SELL'])
      unless validator.valid?(transaction_type)
        fail ArgumentError, "invalid value for \"transaction_type\", must be one of #{validator.allowable_values}."
      end
      @transaction_type = transaction_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          account_id == o.account_id &&
          counter_account_id == o.counter_account_id &&
          currency == o.currency &&
          amount == o.amount &&
          anonymous == o.anonymous &&
          created == o.created &&
          market_value == o.market_value &&
          operation_type == o.operation_type &&
          transaction_type == o.transaction_type &&
          reference == o.reference &&
          transaction_code == o.transaction_code &&
          sender_note == o.sender_note &&
          recipient_note == o.recipient_note &&
          payment_id == o.payment_id &&
          attr == o.attr &&
          address == o.address &&
          tx_id == o.tx_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [account_id, counter_account_id, currency, amount, anonymous, created, market_value, operation_type, transaction_type, reference, transaction_code, sender_note, recipient_note, payment_id, attr, address, tx_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        Tatum.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
